### ISSUE TITLE
Error while reactify an existing django app (name="React_UI")

### ISSUE THREAD

**Issue by choudharyvikash20** [Bonifase/django-reactify#1]
D:\professional\React\Reactify Django\website>python manage.py reactify React_UI
Traceback (most recent call last):
  File "D:\professional\React\Reactify Django\website\manage.py", line 22, in <module>
    main()
  File "D:\professional\React\Reactify Django\website\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\HP\Envs\Uliv\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\HP\Envs\Uliv\lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\HP\Envs\Uliv\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\HP\Envs\Uliv\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\Users\HP\Envs\Uliv\lib\site-packages\reactify\management\commands\reactify.py", line 14, in handle
    subprocess.run(f'''
  File "c:\users\hp\appdata\local\programs\python\python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\hp\appdata\local\programs\python\python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\hp\appdata\local\programs\python\python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 3] The system cannot find the path specified

Facing above issue while run above command. 
What is the issue? I need help.

**Comment by Bonifase** [comment]
I think this [commit](https://github.com/Bonifase/django-reactify/commit/47434b607855359d0dbeade970ab1145513de50d) fixes the issue. See the version update at [1.3.6](https://pypi.org/project/django-reactify/1.3.6/)

**Comment by momati-ninja** [comment]
thats because we are runing on windows :(
